FROM ultralytics/ultralytics
COPY ./app.py /deploy/
# COPY ./requirements.txt /deploy/
WORKDIR /deploy/
# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip3 install numpy
RUN pip3 install Flask
# RUN pip3 install -r requirements.txt
EXPOSE 80
ENTRYPOINT ["python", "app.py"]